### ISSUE TITLE
Add RSS/Atom feed?

### ISSUE THREAD

**Issue by dbertram** [yusukebe/yusu.ke#1]
Hi there!

I don't know if you plan to continue posting English blog posts at https://blog.yusu.ke/, but if you do, a RSS/Atom feed would be great for nosey folx like me that like to read them! 😃 

---

I read your recent post about Hono on the Cloudflare blog (via my feed reader!), then googled your name to see if you had a personal site/blog. I found yusu.ke and poked around a bit and found https://blog.yusu.ke/.

I figured you might keep your personal site in GitHub, which lead me here... although it looks like most of your writing is maybe going to your Japanese blog at https://yusukebe.com/ now?

Either way, I've really enjoyed reading your posts and have been using Hono at work and personally for the last couple of years....it's been great! 🎉 👏

**Comment by yusukebe** [comment]
Hi @dbertram 

Thank you for the comment! I'm glad!

I'm using Astro to create `https://blog.yusu.ke`, though it's not in the public repository (I want to replace it with [HonoX](https://github.com/honojs/honox)). So, if you're interested, you can find the RSS/Atom feature with Astro! And I can consider implementing it.

About English blog posts, I'll keep writing them on `https://blog.yusu.ke` and will write more posts on the Cloudflare blog!

**Comment by yusukebe** [comment]
@dbertram 

Ahhhh. I already implemented the RSS feed. I just forgot to add auto-discovery.

You can subscribe to it from https://blog.yusu.ke/rss.xml !

**Comment by dbertram** [comment]
> Ahhhh. I already implemented the RSS feed. I just forgot to add auto-discovery.
> 
> You can subscribe to it from https://blog.yusu.ke/rss.xml !

Oh, nice! I had tried poking at things like `/feed.xml`, but hadn't tried `rss.xml`. Thank you!
